#docker-compose.yaml
services:
  mongo:
    image: mongo:7
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./back-end/api
    container_name: backend
    ports:
      - "3001:3001"
    env_file:
      - ./back-end/api/.env
    depends_on:
      - mongo

  frontend:
    build: ./front-end/my-app
    container_name: frontend
    ports:
      - "3000:3000"
    # ถ้าอยากโหลด env จากไฟล์ .env.local เข้า container ด้วย
    env_file:
      - ./front-end/my-app/.env.local
    depends_on:
      - backend

volumes:
  mongo-data:


